## Подготовка данных

### Импорты

In [74]:
import pandas as pd

### Загрузка данных

In [75]:
data = pd.read_excel('course_work_ml.xlsx')
pd.set_option('display.max_columns', None)

## Разведочный анализ данных

In [76]:
df = data.copy()

In [77]:
df = df.drop(columns=['Unnamed: 0'], axis = 1)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Columns: 213 entries, IC50, mM to fr_urea
dtypes: float64(107), int64(106)
memory usage: 1.6 MB

In [79]:
null_columns = df.isnull().sum()
print(null_columns[null_columns > 0])

# Есть несколько колонок, у которых есть null значения

MaxPartialCharge       3
MinPartialCharge       3
MaxAbsPartialCharge    3
MinAbsPartialCharge    3
BCUT2D_MWHI            3
BCUT2D_MWLOW           3
BCUT2D_CHGHI           3
BCUT2D_CHGLO           3
BCUT2D_LOGPHI          3
BCUT2D_LOGPLOW         3
BCUT2D_MRHI            3
BCUT2D_MRLOW           3
dtype: int64

In [80]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)
# Удаляем строки с дубликатами

In [81]:
df.describe()

,"IC50, mM","CC50, mM",SI,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,NumRadicalElectrons,MaxPartialCharge,MinPartialCharge,MaxAbsPartialCharge,MinAbsPartialCharge,FpDensityMorgan1,FpDensityMorgan2,FpDensityMorgan3,BCUT2D_MWHI,BCUT2D_MWLOW,BCUT2D_CHGHI,BCUT2D_CHGLO,BCUT2D_LOGPHI,BCUT2D_LOGPLOW,BCUT2D_MRHI,BCUT2D_MRLOW,AvgIpc,BalabanJ,BertzCT,Chi0,Chi0n,Chi0v,Chi1,Chi1n,Chi1v,Chi2n,Chi2v,Chi3n,Chi3v,Chi4n,Chi4v,HallKierAlpha,Ipc,Kappa1,Kappa2,Kappa3,LabuteASA,PEOE_VSA1,PEOE_VSA10,PEOE_VSA11,PEOE_VSA12,PEOE_VSA13,PEOE_VSA14,PEOE_VSA2,PEOE_VSA3,PEOE_VSA4,PEOE_VSA5,PEOE_VSA6,PEOE_VSA7,PEOE_VSA8,PEOE_VSA9,SMR_VSA1,SMR_VSA10,SMR_VSA2,SMR_VSA3,SMR_VSA4,SMR_VSA5,SMR_VSA6,SMR_VSA7,SMR_VSA8,SMR_VSA9,SlogP_VSA1,SlogP_VSA10,SlogP_VSA11,SlogP_VSA12,SlogP_VSA2,SlogP_VSA3,SlogP_VSA4,SlogP_VSA5,SlogP_VSA6,SlogP_VSA7,SlogP_VSA8,SlogP_VSA9,TPSA,EState_VSA1,EState_VSA10,EState_VSA11,EState_VSA2,EState_VSA3,EState_VSA4,EState_VSA5,EState_VSA6,EState_VSA7,EState_VSA8,EState_VSA9,VSA_EState1,VSA_EState10,VSA_EState2,VSA_EState3,VSA_EState4,VSA_EState5,VSA_EState6,VSA_EState7,VSA_EState8,VSA_EState9,FractionCSP3,HeavyAtomCount,NHOHCount,NOCount,NumAliphaticCarbocycles,NumAliphaticHeterocycles,NumAliphaticRings,NumAromaticCarbocycles,NumAromaticHeterocycles,NumAromaticRings,NumHAcceptors,NumHDonors,NumHeteroatoms,NumRotatableBonds,NumSaturatedCarbocycles,NumSaturatedHeterocycles,NumSaturatedRings,RingCount,MolLogP,MolMR,fr_Al_COO,fr_Al_OH,fr_Al_OH_noTert,fr_ArN,fr_Ar_COO,fr_Ar_N,fr_Ar_NH,fr_Ar_OH,fr_COO,fr_COO2,fr_C_O,fr_C_O_noCOO,fr_C_S,fr_HOCCN,fr_Imine,fr_NH0,fr_NH1,fr_NH2,fr_N_O,fr_Ndealkylation1,fr_Ndealkylation2,fr_Nhpyrrole,fr_SH,fr_aldehyde,fr_alkyl_carbamate,fr_alkyl_halide,fr_allylic_oxid,fr_amide,fr_amidine,fr_aniline,fr_aryl_methyl,fr_azide,fr_azo,fr_barbitur,fr_benzene,fr_benzodiazepine,fr_bicyclic,fr_diazo,fr_dihydropyridine,fr_epoxide,fr_ester,fr_ether,fr_furan,fr_guanido,fr_halogen,fr_hdrzine,fr_hdrzone,fr_imidazole,fr_imide,fr_isocyan,fr_isothiocyan,fr_ketone,fr_ketone_Topliss,fr_lactam,fr_lactone,fr_methoxy,fr_morpholine,fr_nitrile,fr_nitro,fr_nitro_arom,fr_nitro_arom_nonortho,fr_nitroso,fr_oxazole,fr_oxime,fr_para_hydroxylation,fr_phenol,fr_phenol_noOrthoHbond,fr_phos_acid,fr_phos_ester,fr_piperdine,fr_piperzine,fr_priamide,fr_prisulfonamd,fr_pyridine,fr_quatN,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
count,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.0,966.000000,966.000000,966.000000,966.000000,969.000000,969.000000,969.000000,966.000000,966.000000,966.000000,966.000000,966.000000,966.000000,966.000000,966.000000,969.000000,9.690000e+02,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,9.690000e+02,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.0,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.0,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.0,969.000000,969.000000,969.000000,969.0,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.0,969.000000,969.0,969.000000,969.0,969.000000,969.0,969.0,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.0,969.0,969.000000,969.000000,969.0,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.0,969.000000,969.000000,969.000000,969.000000,969.000000,969.0,969.0,969.000000,969.000000,969.000000,969.0,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.000000,969.0,969.000000,969.000000,969.000000
mean,220.726223,586.419908,73.967907,10.893712,10.893712,0.179533,-0.960140,0.577633,29.370350,351.486139,327.571885,351.159694,133.234262,0.0,0.237593,-0.408766,0.416837,0.229613,1.143213,1.826831,2.425114,23.371352,9.793534,2.471901,-2.346251,2.472805,-2.402807,6.315108,-0.067736,2.828868,1.841224e+00,764.831615,17.821450,14.647422,14.986543,11.841212,8.709450,9.015053,7.367824,7.717248,5.656862,5.950460,4.183157,4.428000,-1.918847,4.991263e+10,17.162497,6.440851,3.116766,148.033729,12.773702,8.244717,5.062795,3.463765,1.208633,3.407055,6.075143,3.010978,2.901901,1.790286,26.689486,41.544537,16.703245,14.986153,15.871503,15.455147,0.060604,5.373516,11.669253,41.622630,13.749960,38.233277,0.0,5.826507,6.100991,4.565802,3.864426,4.171987,33.558177,8.382740,11.882298,39.624035,31.314347,0.314383,4.083213,0.0,62.081950,12.505151,10.225683,0.144988,13.486185,16.615915,20.419681,18.832421,11.699208,14.368667,20.550567,9.013933,14.596052,1.029662,14.918026,9.292410,2.133777,0.029855,6.667269,3.209608,5.459008,0.557416,0.538683,24.880289,1.305470,4.758514,1.204334,0.888545,2.092879,0.980392,0.517028,1.497420,4.411765,1.179567,5.648091,3.867905,0.937049,0.542828,1.479876,3.590299,3.452764,95.062063,0.054696,0.409701,0.313725,0.015480,0.001032,0.599587,0.031992,0.192982,0.055728,0.055728,0.828689,0.772962,0.043344,0.001032,0.166151,1.334365,0.388029,0.123839,0.0,0.075335,0.084623,0.031992,0.0,0.003096,0.012384,0.379773,0.342621,0.347781,0.008256,0.307534,0.168215,0.0,0.007224,0.0,0.980392,0.0,1.488132,0.0,0.0,0.005160,0.227038,1.040248,0.049536,0.004128,0.617131,0.003096,0.067079,0.053664,0.027864,0.0,0.0,0.194014,0.115583,0.0,0.046440,0.278638,0.085655,0.006192,0.027864,0.012384,0.011352,0.0,0.004128,0.009288,0.182663,0.180599,0.180599,0.0,0.0,0.066047,0.018576,0.023736,0.0,0.025800,0.054696,0.055728,0.012384,0.009288,0.001032,0.001032,0.053664,0.0,0.070175,0.208462,0.007224
std,397.172441,633.624464,695.564665,3.284005,3.284005,0.168928,1.567568,0.213316,12.605779,127.388186,122.037199,127.249801,46.938458,0.0,0.127773,0.075710,0.071686,0.118237,0.242279,0.322220,0.397631,14.708598,0.465884,0.162043,0.166421,0.156214,0.175153,1.097037,0.250027,0.430678,4.520258e-01,437.465117,6.335839,5.207052,5.292790,4.450244,3.154656,3.244607,2.759667,2.849219,2.478540,2.549471,1.939313,2.022429,1.383984,1.276529e+12,6.402396,3.019740,1.731464,52.751389,11.704936,12.738050,8.987260,5.523279,2.651256,7.349470,5.914105,4.985756,6.611756,4.432766,20.740797,21.776577,10.858256,12.567558,13.493707,13.259926,0.565950,6.723552,12.221219,29.719190,16.338139,31.737881,0.0,11.100757,6.239887,7.143601,8.556552,8.034515,23.862560,7.747585,11.018201,26.787814,25.208628,1.408340,7.258604,0.0,45.980973,18.887577,10.602694,0.966840,12.356878,13.985467,13.901377,22.569333,13.726760,20.094512,19.355179,8.546682,17.735949,2.253083,13.609422,15.354622,2.871211,2.459436,7.049580,5.318452,5.772538,1.675162,0.307297,9.106017,1.715143,3.212111,1.441541,1.045436,1.350559,0.999291,0.727251,1.399618,3.220657,1.604087,3.510757,3.296174,1.343472,0.803191,1.344509,1.577983,2.157542,34.580393,0.227502,1.051538,1.006501,0.131613,0.032125,1.273798,0.176069,0.777334,0.229513,0.229513,1.014137,0.930460,0.203735,0.032125,0.443327,1.651341,0.601394,0.332688,0.0,0.307450,0.296433,0.176069,0.0,0.055584,0.110649,1.055409,0.805617,0.708419,0.090533,0.666770,0.428312,0.0,0.084730,0.0,0.999291,0.0,1.434562,0.0,0.0,0.084881,0.483244,1.425647,0.235361,0.064150,1.220078,0.055584,0.254383,0.225469,0.164667,0.0,0.0,0.511768,0.420368,0.0,0.233793,0.739086,0.377424,0.078485,0.164667,0.110649,0.105994,0.0,0.064150,0.106195,0.486033,0.736725,0.736725,0.0,0.0,0.272297,0.221904,0.152304,0.0,0.158619,0.305090,0.263069,0.110649,0.095975,0.032125,0.032125,0.225469,0.0,0.255574,1.231428,0.084730
min,0.003517,0.700808,0.011489,2.321942,2.321942,0.000039,-6.992796,0.059567,9.416667,110.156000,100.076000,110.073165,42.000000,0.0,-0.016706,-0.744036,0.085007,0.002020,0.222222,0.377778,0.577778,14.513946,0.931261,1.834460,-2.721859,1.932099,-2.785712,4.652069,-1.080944,1.787472,2.338384e-07,113.625488,5.560478,4.112077,4.112077,3.860173,2.128962,2.128962,1.301253,1.301253,0.749989,0.749989,0.415115,0.415115,-6.520000,1.071072e+02,4.539509,1.335792,0.444985,46.234269,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.593531,-1.258309,-4.582644,-20.302654,-2.073618,-33.086390,-2.210722,-7.681287,0.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-5.750700,28.088500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
25%,12.515396,99.999345,1.488095,10.006389,10.006389,0.050979,-1.333174,0.442842,18.500000,266.252000,248.200000,266.057909,102.000000,0.0,0.124167,-0.478187,0.361408,0.123910,1.000000,1.642857,2.250000,16.371425,9.689358,2.388521,-2.469199,2.359271,-2.528582,5.774439,-0.157022,2.501580,1.521461e+00,421.423181,13.620956,11.322740,11.501671,8.954327,6.748044,6.856699,5.545865,5.668702,4.085604,4.222598,2.986713,3.145008,-2.890000,2.047821e+04,12.909823,4.389717,2.012002,113.132727,5.316789,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.142387,30.331835,10.682389,6.069221,5.106527,5.783245,0.000000,0.000000,0.000000,19.276334,0.000000,11.649125,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,16.811545,4.736863,0.000000,21.484892,9.984809,0.000000,0.000000,0.0,29.460000,0.000000,4.794537,0.000000,5.601051,6.066367,11.136556,5.563451,0.000000,0.000000,5.316789,4.523095,1.014202,0.000000,4.298543,0.000000,0.203017,-0.836102,0.000000,0.085135,1.336803,0.000000,0.277778,19.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,2.000000,0.000000,0.000000,0.000000,2.000000,2.449200,73.009700,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
50%,45.338355,424.166213,3.900000,12.196496,12.196496,0.123850,-0.419485,0.634372,29.200000,318.373000,296.266000,318.083827,122.000000,0.0,0.255051,-0.393567,0.432834,0.255051,1.155556,1.880000,2.500000,16.566738,9.715702,2.505451,-2.358527,2.484733,-2.396486,5.941428,-0.104610,2.820857,1.829943e+00,670.536976,16.164926,13.387517,13.834351,10.536843,7.957209,8.185034,6.786944,7.273939,5.137593,5.563432,3.860024,4.084453,-1.570000,1.204932e+05,15.801966,5.707671,2.696225,133.841485,10.006437,5.693928,0.000000,0.000000,0.000000,0.000000,4.794537,0.000000,0.000000,0.000000,23.752980,38.063890,17.168516,12.462662,14.260541,11.752550,0.000000,4.899910,5.917906,40.033676,10.633577,35.392371,0.0,0.000000,5.316789,0.000000,0.000000,0.000000,28.022038,6.176299,11.332897,39.027845,29.160952,0.000000,0.000000,0.0,49.770000,5.601051,5.106527,0.000000,11.446105,12.338728,17.753718,12.673249,6.263163,6.066367,17.468829,5.733667,6.655736,0.000000,12.747014,4.013653,1.920132,0.622905,5.623598,3.614416,4.226103,0.000000,0.545455,22.000000,1.000000,4.000000,1.000000,1.000000,2.000000,1.000000,0.000000,1.000000,4.000000,1.000000,5.000000,3.000000,0.000000,0.000000,1.000000,3.000000,3.432800,86.689500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,1.000000,0.0,1.000000,0.0,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
75%,231.373089,891.776925,16.375000,13.178870,13.178870,0.291020,0.007873,0.742483,38.600000,413.670000,389.224000,413.352640,154.000000,0.0,0.335895,-0.357741,0.478225,0.330890,1.333333,2.055556,2.700000,32.092047,9.972710,2.590939,-2.235779,2.603245,-2.323815,6.690661,0.059814,3.093670,2.072977e+00,987.176170,20.916003,16.691311,17.076606,14.059856,9.999157,10.441559,8.671958,9.131481,6.679793,7.027775,4.854159,5.172988,-0.810000,5.643087e+06,19.780379,7.567653,3.771279,173.927650,14.953561,11.566733,5.783245,5.907180,0.000000,5.969305,9.589074,4.794537,0.000000,0.000000,38.841158,51.258560,23.282242,20.546915,23.364603,23.017697,0.000000,9.799819,17.753718,57.339744,18.406301,64.718375,0.0,5.749512,10.165653,5.687386,5.749512,11.336786,46.283879,12.841643,16.747887,50.391665,48.530937,0.000000,6.076020,0.0,83.760000,18.115113,15.007592,0.000000,18.125839,22.439866,27.302019,25.683286,19.056471,24.265468,31.071979,13.890877,20.885832,0.971351,22.992662,12.054961,4.067682,1.439940,10.615848,5.866102,7.615276,0.000000,0.833333,29.000000,2.000000,6.000000,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,5.000000,2.000000,8.000000,5.000000,2.000000,1.000000,2.000000,4.000000,4.537720,111.863200,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,2.000000,1.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,2.000000,0.0,2.000000,0.0,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
max,4128.529377,4538.976189,15620.600000,15.933463,15.933463,1.374614,1.374614,0.947265,60.272727,904.777000,856.393000,904.248467,350.000000,0.0,0.572596,-0.085007,0.744036,0.507387,1.750000,2.625000,3.266667,126.912704,10.708899,2.822293,-1.713605,2.791427,-1.647760,14.111964,1.170324,3.952629,3.793185e+00,2263.926215,45.763973,35.986976,35.986976,29.800748,22.213426,22.213426,20.180938,20.180938,16.476639,16.476639,12.479916,12.479916,0.270000,3.951781e+13,46.908624,20.374977,12.666255,353.328713,118.909965,107.923797,47.413913,29.507868,17.721539,113.560901,34.192377,43.457663,44.612417,23.523770,128.895212,161.062080,52.282252,65.447564,118.909965,68.411024,5.531129,59.057853,57.356731,174.368015,104.716102,132.959685,0.0,57.495118,33.158041,39.797093,57.495118,45.875452,213.138160,43.553732,52.255323,184.077100,126.698894,19.641034,45.042488,0.0,407.500000,187.446090,81.392448,13.171245,69.229627,93.263558,96.560194,270.327123,62.235593,126.852428,150.952614,56.607036,122.591643,15.553441,67.303382,156.359460,12.358433,6.583783,32.812084,33.923275,36.982751,10.183618,1.000000,63.000000,15.000000,25.000000,7.000000,6.000000,7.000000,4.000000,5.000000,7.000000,25.000000,15.000000,25.000000,28.000000,6.000000,6.000000,7.000000,9.000000,12.822200,236.253400,1.000000,12.000000,12.000000,2.000000,1.000000,12.000000,1.000000,8.000000,1.000000,1.000000,5.000000,5.000000,1.000000,1.000000,2.000000,12.000000,3.000000,2.000000,0.0,2.000000,2.000000,1.000000,0.0,1.000000,1.000000,9.000000,8.000000,4.000000,1.000000,4.000000,3.000000,0.0,1.000000,0.0,4.000000,0.0,7.000000,0.0,0.0,2.000000,4.000000,8.000000,2.000000,1.000000,9.000000,1.000000,2.000000,1.000000,1.000000,0.0,0.0,3.000000,3.000000,0.0,2.000000,4.000000,2.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,2.000000,4.000000,8.000000,8.000000,0.0,0.0,2.000000,6.000000,1.000000,0.0,1.000000,4.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,20.000000,1.000000

In [82]:
df.head()

,"IC50, mM","CC50, mM",SI,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,NumRadicalElectrons,MaxPartialCharge,MinPartialCharge,MaxAbsPartialCharge,MinAbsPartialCharge,FpDensityMorgan1,FpDensityMorgan2,FpDensityMorgan3,BCUT2D_MWHI,BCUT2D_MWLOW,BCUT2D_CHGHI,BCUT2D_CHGLO,BCUT2D_LOGPHI,BCUT2D_LOGPLOW,BCUT2D_MRHI,BCUT2D_MRLOW,AvgIpc,BalabanJ,BertzCT,Chi0,Chi0n,Chi0v,Chi1,Chi1n,Chi1v,Chi2n,Chi2v,Chi3n,Chi3v,Chi4n,Chi4v,HallKierAlpha,Ipc,Kappa1,Kappa2,Kappa3,LabuteASA,PEOE_VSA1,PEOE_VSA10,PEOE_VSA11,PEOE_VSA12,PEOE_VSA13,PEOE_VSA14,PEOE_VSA2,PEOE_VSA3,PEOE_VSA4,PEOE_VSA5,PEOE_VSA6,PEOE_VSA7,PEOE_VSA8,PEOE_VSA9,SMR_VSA1,SMR_VSA10,SMR_VSA2,SMR_VSA3,SMR_VSA4,SMR_VSA5,SMR_VSA6,SMR_VSA7,SMR_VSA8,SMR_VSA9,SlogP_VSA1,SlogP_VSA10,SlogP_VSA11,SlogP_VSA12,SlogP_VSA2,SlogP_VSA3,SlogP_VSA4,SlogP_VSA5,SlogP_VSA6,SlogP_VSA7,SlogP_VSA8,SlogP_VSA9,TPSA,EState_VSA1,EState_VSA10,EState_VSA11,EState_VSA2,EState_VSA3,EState_VSA4,EState_VSA5,EState_VSA6,EState_VSA7,EState_VSA8,EState_VSA9,VSA_EState1,VSA_EState10,VSA_EState2,VSA_EState3,VSA_EState4,VSA_EState5,VSA_EState6,VSA_EState7,VSA_EState8,VSA_EState9,FractionCSP3,HeavyAtomCount,NHOHCount,NOCount,NumAliphaticCarbocycles,NumAliphaticHeterocycles,NumAliphaticRings,NumAromaticCarbocycles,NumAromaticHeterocycles,NumAromaticRings,NumHAcceptors,NumHDonors,NumHeteroatoms,NumRotatableBonds,NumSaturatedCarbocycles,NumSaturatedHeterocycles,NumSaturatedRings,RingCount,MolLogP,MolMR,fr_Al_COO,fr_Al_OH,fr_Al_OH_noTert,fr_ArN,fr_Ar_COO,fr_Ar_N,fr_Ar_NH,fr_Ar_OH,fr_COO,fr_COO2,fr_C_O,fr_C_O_noCOO,fr_C_S,fr_HOCCN,fr_Imine,fr_NH0,fr_NH1,fr_NH2,fr_N_O,fr_Ndealkylation1,fr_Ndealkylation2,fr_Nhpyrrole,fr_SH,fr_aldehyde,fr_alkyl_carbamate,fr_alkyl_halide,fr_allylic_oxid,fr_amide,fr_amidine,fr_aniline,fr_aryl_methyl,fr_azide,fr_azo,fr_barbitur,fr_benzene,fr_benzodiazepine,fr_bicyclic,fr_diazo,fr_dihydropyridine,fr_epoxide,fr_ester,fr_ether,fr_furan,fr_guanido,fr_halogen,fr_hdrzine,fr_hdrzone,fr_imidazole,fr_imide,fr_isocyan,fr_isothiocyan,fr_ketone,fr_ketone_Topliss,fr_lactam,fr_lactone,fr_methoxy,fr_morpholine,fr_nitrile,fr_nitro,fr_nitro_arom,fr_nitro_arom_nonortho,fr_nitroso,fr_oxazole,fr_oxime,fr_para_hydroxylation,fr_phenol,fr_phenol_noOrthoHbond,fr_phos_acid,fr_phos_ester,fr_piperdine,fr_piperzine,fr_priamide,fr_prisulfonamd,fr_pyridine,fr_quatN,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,6.239374,175.482382,28.125000,5.094096,5.094096,0.387225,0.387225,0.417362,42.928571,384.652,340.300,384.350449,158,0,0.038844,-0.293526,0.293526,0.038844,0.642857,1.035714,1.321429,14.822266,9.700470,2.600532,-2.343082,2.644698,-2.322229,5.944519,0.193481,3.150503,1.164038,611.920301,20.208896,19.534409,19.534409,13.127794,12.204226,12.204226,12.058078,12.058078,10.695991,10.695991,7.340247,7.340247,-0.66,2.187750e+06,20.606247,6.947534,2.868737,173.630124,0.000000,0.0,0.0,0.0,0.0,0.0,9.984809,0.0,0.0,0.0,54.384066,74.032366,35.342864,0.000000,0.000000,11.423370,0.0,0.000000,43.480583,105.750639,13.089513,0.00000,0,0.0,0.000000,0.000000,0.0,0.0,24.512883,0.000000,33.495774,105.750639,9.984809,0.0,0.0,0,24.72,0.0,0.0,0.0,0.000000,21.659962,24.925325,64.208216,11.42337,0.0,41.542423,9.984809,0.00000,0.0,10.188192,0.000000,4.807589,1.764908,0.000000,13.258223,16.981087,0.000000,0.923077,28,0,2,4,0,4,0,0,0,2,0,2,7,4,0,4,4,7.1212,121.5300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0
1,0.771831,5.402819,7.000000,3.961417,3.961417,0.533868,0.533868,0.462473,45.214286,388.684,340.300,388.381750,162,0,0.012887,-0.313407,0.313407,0.012887,0.607143,1.000000,1.285714,14.975110,9.689226,2.614066,-2.394690,2.658342,-2.444817,5.134527,0.120322,3.150503,1.080362,516.780124,20.208896,19.794682,19.794682,13.127794,12.595754,12.595754,12.648545,12.648545,11.473090,11.473090,8.180905,8.180905,-0.08,2.187750e+06,21.163454,7.257648,3.027177,174.939204,10.633577,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,54.384066,97.951860,12.083682,0.000000,0.000000,0.000000,0.0,10.633577,33.495774,117.834321,13.089513,0.00000,0,0.0,10.633577,0.000000,0.0,0.0,25.173194,0.000000,33.495774,105.750639,0.000000,0.0,0.0,0,24.06,0.0,0.0,0.0,0.000000,21.659962,23.919494,77.297729,0.00000,0.0,52.176000,0.000000,0.00000,0.0,0.000000,7.922833,2.153503,1.914377,1.536674,14.135381,17.670565,0.000000,1.000000,28,2,2,4,0,4,0,0,0,2,2,2,9,4,0,4,4,6.1556,120.5074,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0
2,223.808778,161.142320,0.720000,2.627117,2.627117,0.543231,0.543231,0.260923,42.187500,446.808,388.344,446.458903,186,0,0.094802,-0.325573,0.325573,0.094802,0.562500,0.906250,1.156250,15.353938,9.681293,2.665274,-2.477203,2.679014,-2.565224,5.117187,-0.922902,3.214947,1.219066,643.620154,23.794682,23.689110,23.689110,14.595754,14.249005,14.249005,15.671216,15.671216,13.402236,13.402236,10.140303,10.140303,-0.08,8.610751e+06,25.026112,7.709373,3.470070,201.238858,8.966062,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,41.542423,74.032366,23.671624,53.363882,8.966062,0.000000,0.0,0.000000,33.495774,117.834321,41.280201,0.00000,0,0.0,0.000000,0.000000,0.0,0.0,62.329944,0.000000,33.495774,105.750639,0.000000,0.0,0.0,0,0.00,0.0,0.0,0.0,0.000000,21.659962,23.919494,86.263791,0.00000,0.0,69.733111,0.000000,2.51763,0.0,0.000000,0.000000,2.184127,1.930720,1.738402,14.491619,18.287216,10.183618,1.000000,32,0,2,4,0,4,0,0,0,0,0,2,9,4,0,4,4,7.1292,138.4528,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,3,0
3,1.705624,107.855654,63.235294,5.097360,5.097360,0.390603,0.390603,0.377846,41.862069,398.679,352.311,398.366099,164,0,0.038844,-0.293526,0.293526,0.038844,0.620690,1.000000,1.310345,14.821216,9.700497,2.600529,-2.342885,2.644709,-2.322030,5.944502,0.193510,3.179270,1.120513,626.651366,20.916003,20.241516,20.241516,13.627794,12.704226,12.704226,12.411631,12.411631,10.945991,10.945991,7.517023,7.517023,-0.66,3.572142e+06,21.567454,7.485204,3.263848,179.995066,0.000000,0.0,0.0,0.0,0.0,0.0,9.984809,0.0,0.0,0.0,60.804888,74.032366,35.342864,0.000000,0.000000,11.423370,0.0,0.000000,43.480583,112.171461,13.089513,0.00000,0,0.0,0.000000,0.000000,0.0,0.0,24.512883,0.000000,33.495774,112.171461,9.984809,0.0,0.0,0,24.72,0.0,0.0,0.0,0.000000,21.659962,24.925325,70.629038,11.42337,0.0,41.542423,9.984809,0.00000,0.0,10.194720,0.000000,4.827852,1.769975,0.000000,14.695439,17.012013,0.000000,0.925926,29,0,2,4,0,4,0,0,0,2,0,2,8,4,0,4,4,7.5113,126.1470,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0
4,107.131532,139.270991,1.300000,5.150510,5.150510,0.270476,0.270476,0.429038,36.514286,466.713,424.377,466.334799,184,0,0.062897,-0.257239,0.257239,0.062897,0.600000,0.971429,1.257143,14.831112,9.700386,2.602486,-2.342009,2.648473,-2.318893,5.963448,0.193687,3.337074,1.136678,1101.164252,24.639617,22.617677,22.617677,16.526773,13.868825,13.868825,13.613700,13.613700,11.833480,11.833480,8.119076,8.119076,-2.22,1.053758e+08,23.194917,7.639211,3.345855,211.919602,0.000000,0.0,0.0,0.0,0.0,0.0,9.984809,0.0,0.0,0.0,65.807891,103.003916,22.253351,11.374773,0.000000,22.798143,0.0,0.000000,43.480583,86.488175,0.000000,59.65784,0,0.0,0.000000,11.374773,0.0,0.0,11.423370,6.420822,33.495774,91.194256,58.515746,0.0,0.0,0,24.72,0.0,0.0,0.0,10.829981,10.829981,29.631406,61.075203,0.00000,0.0,90.073360,9.984809,0.00000,0.0,10.301020,0.000000,9.071783,1.605178,17.869058,8.627311,14.692318,0.000000,0.575758,35,0,2,4,0,4,2,0,2,2,0,2,4,4,0,4,6,9.1148,148.3380,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## Преобразование данных

### Удаление столбцов

In [83]:
stds = df.std(numeric_only=True)
uninformative_cols = stds[stds == 0].index

print(uninformative_cols)

# Удалим  дублирующиеся или неинформативные столбцы с нулевым стандартным отклонением

Index(['NumRadicalElectrons', 'SMR_VSA8', 'SlogP_VSA9', 'fr_N_O', 'fr_SH',
       'fr_azide', 'fr_barbitur', 'fr_benzodiazepine', 'fr_diazo',
       'fr_dihydropyridine', 'fr_isocyan', 'fr_isothiocyan', 'fr_lactam',
       'fr_nitroso', 'fr_phos_acid', 'fr_phos_ester', 'fr_prisulfonamd',
       'fr_thiocyan'],
      dtype='object')

In [84]:
df = df.drop(columns=uninformative_cols)

### Работа с null значениями

In [85]:
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

# Заменяем null на медианное значение столбца

In [86]:
null_columns = df.isnull().sum()
print(null_columns[null_columns > 0])

# null больше нет

Series([], dtype: int64)

### Работа с выбросами

In [87]:
for col in ['IC50, mM', 'CC50, mM', 'SI']:
    if col in df.columns:
        q99 = df[col].quantile(0.99)
        df = df[df[col] <= q99]


# Удаляем строки, где значение "IC50, mM", "CC50, mM" и "SI" выше 99 перцентиля

## Выгрузка обработанного файла

In [88]:
df.to_csv('processed_data.csv', index=False)

In [90]:
df

,"IC50, mM","CC50, mM",SI,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,MaxPartialCharge,MinPartialCharge,MaxAbsPartialCharge,MinAbsPartialCharge,FpDensityMorgan1,FpDensityMorgan2,FpDensityMorgan3,BCUT2D_MWHI,BCUT2D_MWLOW,BCUT2D_CHGHI,BCUT2D_CHGLO,BCUT2D_LOGPHI,BCUT2D_LOGPLOW,BCUT2D_MRHI,BCUT2D_MRLOW,AvgIpc,BalabanJ,BertzCT,Chi0,Chi0n,Chi0v,Chi1,Chi1n,Chi1v,Chi2n,Chi2v,Chi3n,Chi3v,Chi4n,Chi4v,HallKierAlpha,Ipc,Kappa1,Kappa2,Kappa3,LabuteASA,PEOE_VSA1,PEOE_VSA10,PEOE_VSA11,PEOE_VSA12,PEOE_VSA13,PEOE_VSA14,PEOE_VSA2,PEOE_VSA3,PEOE_VSA4,PEOE_VSA5,PEOE_VSA6,PEOE_VSA7,PEOE_VSA8,PEOE_VSA9,SMR_VSA1,SMR_VSA10,SMR_VSA2,SMR_VSA3,SMR_VSA4,SMR_VSA5,SMR_VSA6,SMR_VSA7,SMR_VSA9,SlogP_VSA1,SlogP_VSA10,SlogP_VSA11,SlogP_VSA12,SlogP_VSA2,SlogP_VSA3,SlogP_VSA4,SlogP_VSA5,SlogP_VSA6,SlogP_VSA7,SlogP_VSA8,TPSA,EState_VSA1,EState_VSA10,EState_VSA11,EState_VSA2,EState_VSA3,EState_VSA4,EState_VSA5,EState_VSA6,EState_VSA7,EState_VSA8,EState_VSA9,VSA_EState1,VSA_EState10,VSA_EState2,VSA_EState3,VSA_EState4,VSA_EState5,VSA_EState6,VSA_EState7,VSA_EState8,VSA_EState9,FractionCSP3,HeavyAtomCount,NHOHCount,NOCount,NumAliphaticCarbocycles,NumAliphaticHeterocycles,NumAliphaticRings,NumAromaticCarbocycles,NumAromaticHeterocycles,NumAromaticRings,NumHAcceptors,NumHDonors,NumHeteroatoms,NumRotatableBonds,NumSaturatedCarbocycles,NumSaturatedHeterocycles,NumSaturatedRings,RingCount,MolLogP,MolMR,fr_Al_COO,fr_Al_OH,fr_Al_OH_noTert,fr_ArN,fr_Ar_COO,fr_Ar_N,fr_Ar_NH,fr_Ar_OH,fr_COO,fr_COO2,fr_C_O,fr_C_O_noCOO,fr_C_S,fr_HOCCN,fr_Imine,fr_NH0,fr_NH1,fr_NH2,fr_Ndealkylation1,fr_Ndealkylation2,fr_Nhpyrrole,fr_aldehyde,fr_alkyl_carbamate,fr_alkyl_halide,fr_allylic_oxid,fr_amide,fr_amidine,fr_aniline,fr_aryl_methyl,fr_azo,fr_benzene,fr_bicyclic,fr_epoxide,fr_ester,fr_ether,fr_furan,fr_guanido,fr_halogen,fr_hdrzine,fr_hdrzone,fr_imidazole,fr_imide,fr_ketone,fr_ketone_Topliss,fr_lactone,fr_methoxy,fr_morpholine,fr_nitrile,fr_nitro,fr_nitro_arom,fr_nitro_arom_nonortho,fr_oxazole,fr_oxime,fr_para_hydroxylation,fr_phenol,fr_phenol_noOrthoHbond,fr_piperdine,fr_piperzine,fr_priamide,fr_pyridine,fr_quatN,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiophene,fr_unbrch_alkane,fr_urea
0,6.239374,175.482382,28.125000,5.094096,5.094096,0.387225,0.387225,0.417362,42.928571,384.652,340.300,384.350449,158,0.038844,-0.293526,0.293526,0.038844,0.642857,1.035714,1.321429,14.822266,9.700470,2.600532,-2.343082,2.644698,-2.322229,5.944519,0.193481,3.150503,1.164038,611.920301,20.208896,19.534409,19.534409,13.127794,12.204226,12.204226,12.058078,12.058078,10.695991,10.695991,7.340247,7.340247,-0.66,2.187750e+06,20.606247,6.947534,2.868737,173.630124,0.000000,0.000000,0.0,0.00000,0.0,0.000000,9.984809,0.000000,0.000000,0.0,54.384066,74.032366,35.342864,0.000000,0.000000,11.423370,0.0,0.000000,43.480583,105.750639,13.089513,0.000000,0.0,0.000000,0.000000,0.0,0.000000,24.512883,0.000000,33.495774,105.750639,9.984809,0.0,0.0,24.72,0.000000,0.000000,0.0,0.000000,21.659962,24.925325,64.208216,11.423370,0.000000,41.542423,9.984809,0.000000,0.000000,10.188192,0.000000,4.807589,1.764908,0.000000,13.258223,16.981087,0.000000,0.923077,28,0,2,4,0,4,0,0,0,2,0,2,7,4,0,4,4,7.1212,121.5300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0
1,0.771831,5.402819,7.000000,3.961417,3.961417,0.533868,0.533868,0.462473,45.214286,388.684,340.300,388.381750,162,0.012887,-0.313407,0.313407,0.012887,0.607143,1.000000,1.285714,14.975110,9.689226,2.614066,-2.394690,2.658342,-2.444817,5.134527,0.120322,3.150503,1.080362,516.780124,20.208896,19.794682,19.794682,13.127794,12.595754,12.595754,12.648545,12.648545,11.473090,11.473090,8.180905,8.180905,-0.08,2.187750e+06,21.163454,7.257648,3.027177,174.939204,10.633577,0.000000,0.0,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,54.384066,97.951860,12.083682,0.000000,0.000000,0.000000,0.0,10.633577,33.495774,117.834321,13.089513,0.000000,0.0,10.633577,0.000000,0.0,0.000000,25.173194,0.000000,33.495774,105.750639,0.000000,0.0,0.0,24.06,0.000000,0.000000,0.0,0.000000,21.659962,23.919494,77.297729,0.000000,0.000000,52.176000,0.000000,0.000000,0.000000,0.000000,7.922833,2.153503,1.914377,1.536674,14.135381,17.670565,0.000000,1.000000,28,2,2,4,0,4,0,0,0,2,2,2,9,4,0,4,4,6.1556,120.5074,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0
2,223.808778,161.142320,0.720000,2.627117,2.627117,0.543231,0.543231,0.260923,42.187500,446.808,388.344,446.458903,186,0.094802,-0.325573,0.325573,0.094802,0.562500,0.906250,1.156250,15.353938,9.681293,2.665274,-2.477203,2.679014,-2.565224,5.117187,-0.922902,3.214947,1.219066,643.620154,23.794682,23.689110,23.689110,14.595754,14.249005,14.249005,15.671216,15.671216,13.402236,13.402236,10.140303,10.140303,-0.08,8.610751e+06,25.026112,7.709373,3.470070,201.238858,8.966062,0.000000,0.0,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,41.542423,74.032366,23.671624,53.363882,8.966062,0.000000,0.0,0.000000,33.495774,117.834321,41.280201,0.000000,0.0,0.000000,0.000000,0.0,0.000000,62.329944,0.000000,33.495774,105.750639,0.000000,0.0,0.0,0.00,0.000000,0.000000,0.0,0.000000,21.659962,23.919494,86.263791,0.000000,0.000000,69.733111,0.000000,2.517630,0.000000,0.000000,0.000000,2.184127,1.930720,1.738402,14.491619,18.287216,10.183618,1.000000,32,0,2,4,0,4,0,0,0,0,0,2,9,4,0,4,4,7.1292,138.4528,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,3,0
3,1.705624,107.855654,63.235294,5.097360,5.097360,0.390603,0.390603,0.377846,41.862069,398.679,352.311,398.366099,164,0.038844,-0.293526,0.293526,0.038844,0.620690,1.000000,1.310345,14.821216,9.700497,2.600529,-2.342885,2.644709,-2.322030,5.944502,0.193510,3.179270,1.120513,626.651366,20.916003,20.241516,20.241516,13.627794,12.704226,12.704226,12.411631,12.411631,10.945991,10.945991,7.517023,7.517023,-0.66,3.572142e+06,21.567454,7.485204,3.263848,179.995066,0.000000,0.000000,0.0,0.00000,0.0,0.000000,9.984809,0.000000,0.000000,0.0,60.804888,74.032366,35.342864,0.000000,0.000000,11.423370,0.0,0.000000,43.480583,112.171461,13.089513,0.000000,0.0,0.000000,0.000000,0.0,0.000000,24.512883,0.000000,33.495774,112.171461,9.984809,0.0,0.0,24.72,0.000000,0.000000,0.0,0.000000,21.659962,24.925325,70.629038,11.423370,0.000000,41.542423,9.984809,0.000000,0.000000,10.194720,0.000000,4.827852,1.769975,0.000000,14.695439,17.012013,0.000000,0.925926,29,0,2,4,0,4,0,0,0,2,0,2,8,4,0,4,4,7.5113,126.1470,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0
4,107.131532,139.270991,1.300000,5.150510,5.150510,0.270476,0.270476,0.429038,36.514286,466.713,424.377,466.334799,184,0.062897,-0.257239,0.257239,0.062897,0.600000,0.971429,1.257143,14.831112,9.700386,2.602486,-2.342009,2.648473,-2.318893,5.963448,0.193687,3.337074,1.136678,1101.164252,24.639617,22.617677,22.617677,16.526773,13.868825,13.868825,13.613700,13.613700,11.833480,11.833480,8.119076,8.119076,-2.22,1.053758e+08,23.194917,7.639211,3.345855,211.919602,0.000000,0.000000,0.0,0.00000,0.0,0.000000,9.984809,0.000000,0.000000,0.0,65.807891,103.003916,22.253351,11.374773,0.000000,22.798143,0.0,0.000000,43.480583,86.488175,0.000000,59.657840,0.0,0.000000,11.374773,0.0,0.000000,11.423370,6.420822,33.495774,91.194256,58.515746,0.0,0.0,24.72,0.000000,0.000000,0.0,10.829981,10.829981,29.631406,61.075203,0.000000,0.000000,90.073360,9.984809,0.000000,0.000000,10.301020,0.000000,9.071783,1.605178,17.869058,8.627311,14.692318,0.000000,0.575758,35,0,2,4,0,4,2,0,2,2,0,2,4,4,0,4,6,9.1148,148.3380,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,31.000104,34.999650,1.129017,12.934891,12.934891,0.048029,-0.476142,0.382752,49.133333,414.542,380.270,414.240624,164,0.317890,-0.468587,0.468587,0.317890,1.133333,1.866667,2.533333,16.586886,9.344314,2.726237,-2.677345,2.739076,-2.646743,5.980114,-0.196385,3.023764,1.646946,857.600295,21.637464,18.825334,18.825334,14.097861,11.665192,11.665192,11.409461,11.409461,10.058026,10.058026,8.981266,8.981266,-1.65,6.242348e+06,20.263719,6.198453,2.219273,178.490760,9.473726,0.000000,0.0,0.00000,0.0,17.907916,14.383612,0.000000,0.000000,0.0,38.841158,68.114460,5.414990,24.360600,23.857337,17.907916,0.0,0.000000,51.752408,66.219879,7.109798,11.649125,0.0,0.000000,0.000000,0.0,0.000000,25.017713,23.857337,51.752408,66.219879,11.649125,0.0,0.0,69.67,5.414990,14.383612,0.0,52.409521,11.835812,38.524930,12.682902,0.000000,0.000000,33.770969,9.473726,10.503509,0.000000,38.515343,0.000000,0.498752,-0.405436,0.000000,7.985276,8.824371,1.494852,0.800000,30,0,5,5,1,6,0,0,0,5,0,5,2,3,1,4,6,4.3002,109.8350,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,1,0,3,2,0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
997,31.999934,33.999415,1.062484,13.635345,13.635345,0.030329,-0.699355,0.369425,44.542857,485.621,446.309,485.277738,192,0.327562,-0.467493,0.467493,0.327562,1.085714,1.800000,2.457143,16.586914,9.343622,2.725543,-2.679467,2.738755,-2.655659,5.980828,-0.187625,3.130958,1.535171,1016.917688,25.499271,21.810933,21.810933,16.402391,13.274017,13.274017,12.636189,12.636189,10.827369,10.827369,9.372775,9.372775,-2.18,5.897229e+07,24.511583,7.908743,3.147136,207.296970,14.790515,6.041841,0.0,5.90718,0.0,17.907916,14.383612,4.794537,0.000000,0.0,45.764895,68.114460,10.829981,18.945610,28.651875,23.815096,0.0,5.316789,51.752408,79.185457,7.109798,11.649125,0.0,5.316789,0.000000,0.0,0.000000,36.966734,28.651875,51.752408,73.143616,11.649125,0.0,0.0,98.77,23.344043,19.178149,0.0,52.347395,5.917906,38.524930,12.682902,6.923737,0.000000,39.087758,9.473726,10.086396,0.000000,51.516353,2.923049,0.162524,-1.300354,-0.699355,7.521836,10.378794,1.327425,0.785714,35,1,7,5,1,6,0,0,0,6,1,7,4,3,1,4,6,3.8049,127.4397,0,0,0,0,0,0,0,0,0,0,4,4,0,0,0,0,1,0,0,0,0,0,0,0,2,1,0,0,0,0,0,1,0,3,2,0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
998,30.999883,33.999458,1.096761,13.991690,13.991690,0.026535,-0.650790,0.284923,41.973684,545.742,502.398,545.281109,210,0.327887,-0.467485,0.467485,0.327887,1.157895,1.894737,2.552632,32.166365,9.343613,2.725818,-2.679527,2.738943,-2.656447,7.980998,-0.187687,3.204255,1.493776,1070.961298,27.620591,23.633394,24.449891,17.940396,14.301838,15.695685,13.248561,14.234160,11.326709,11.970659,9.725583,10.196987,-1.83,2.627956e+08,27.726151,9.668673,3.822745,230.149965,14.790515,6.041841,0.0,5.90718,0.0,17.907916,14.383612,4.794537,11.761885,0.0,45.764895,79.620167,10.829981,18.945610,28.651875,35.576981,0.0,5.316789,51.752408,78.682541,19.118420,11.649125,0.0,5.316789,0.000000,0.0,11.761885,48.975357,28.651875,51.752408,72.640700,11.649125,0.0,0.0,98.77,28.759033,19.178149,0.0,46.932405,12.338728,44.277783,12.682902,11.761885,6.255769,39.087758,9.473726,10.305031,1.639399,52.527620,3.081660,0.139799,-0.487671,-0.650790,10.055493,8.774745,1.364715,0.800000,38,1,7,5,1,6,0,0,0,7,1,8,7,3,1,4,6,4.5381,144.7647,0,0,0,0,0,0,0,0,0,0,4,4,0,0,0,0,1,0,0,0,0,0,0,0,2,1,0,0,0,0,0,1,0,3,2,0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
999,31.998959,32.999644,1.031272,13.830180,13.830180,0.146522,-1.408652,0.381559,39.000000,522.635,480.299,522.282883,208,0.312509,-0.468755,0.468755,0.312509,0.756757,1.351351,1.864865,16.540061,9.364015,2.730109,-2.652209,2.704027,-2.678553,5.950258,-0.225309,2.887043,2.325807,957.299494,27.921921,23.380977,23.380977,17.309003,13.174959,13.174959,11.893254,11.893254,10.158570,10.158570,8.609327,8.609327,-2.45,7.702780e+07,29.111081,10.369092,4.164473,218.836986,18.947452,5.783245,0.0,0.00000,0.0,23.877221,23.972686,0.000000,0.000000,0.0,27.192033,56.278648,11.835812,51.104983,42.920138,29.660466,0.0,0.000000,51.752408,66.219879,28.439190,0.000000,0.0,0.000000,0.000000,0.0,0.000000,58.099656,42.920138,51.752408,66.219879,0.000000,0.0,0.0,122.27,63.742418,23.972686,0.0,30.512100,19.262465,6.420822,28.439190,13.847474,6.923737,6.923737,18.947452,20.885832,0.000000,67.303382,0.000000,-2.785593,-6.848660,0.000000,2.955837,7.488627,5.083909,0.821429,37,0,9,3,0,3,0,0,0,9,0,9,6,3,0,3,3,3.3649,131.7080,0,0,0,0,0,0,0,0,0,0,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,4,4,0,0,0,0,0,0,0,1,1,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1000,99.999531,99.999531,1.000000,13.380863,13.380863,0.002425,-0.447978,0.452565,48.580645,426.597,388.293,426.277010,170,0.311311,-0.468587,0.468587,0.311311,1.064516,1.774194,2.451613,16.525216,9.330327,2.704274,-2.696212,2.737481,-2.668850,5.978085,-0.201381,2.740713,1.651446,870.462214,22.344571,19.831299,19.831299,14.597861,12.464050,12.464050,12.101953,12.101953,10.667206,10.667206,9.563076,9.563076,-1.45,9.086032e+06,21.398566,6.776167,2.566599,186.107099,4.736863,11.566490,0.0,0.00000,0.0,5.969305,14.383612,0.000000,0.000000,0.0,38.841158,68.114460,30.092446,12.524788,19.120475,17.535795,0.0,0.000000,51.752408,79.061522,7.109798,11.649125,0.0,0.000000,0.000000,0.0,0.000000,24.645593,19.120475,51.752408,79.061522,11.649125,0.0,0.0,60.44,5.414990,14.383612,0.0,40.470910,36.243945,38.524930,12.682902,0.000000,0.000000,33.770969,4.736863,5.298868,0.000000,39.472742,0.000000,0.776999,1.605640,0.000000,9.247616,8.999949,1.514853,0.814815,31,0,4,6,0,6,0,0,0,4,0,4,2,4,0,4,6,5.1488,117.9840,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,2,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0